### ISSUE TITLE
Rofication not pulling in notifications

### ISSUE THREAD

**Issue by vredesbyyrd** [DaveDavenport/Rofication#1]
First, this is an awesome solution for desktop notifications. Thank you for sharing it. 

I am trying to use it with a budgie/arch install. There is a package in the aur, so i used that. I created a .desktop file in ~/.config/autostart to start the daemon at boot, which seems to be working fine. As far as I know, budgie uses the same protocols to display notifications as gnome. 

My problem is i cant get this to pull in any notifications. And I really have no idea how to troubleshoot it. Cant find evidence of problems in any logs. 

Any tips would be appreciated. And apoligies for the lack of useful information. 

EDIT: 

I tried using this on my daily driver which runs gnome. I started the daemon with: 

    nohup rofication-daemon.py 0<&- &>/dev/null & 

Rofi-top shows the daemon is running. When i try to run the gui via cli, It prints this error: 

    Traceback (most recent call last):
    File "/usr/bin/rofication-gui.py", line 77, in <module>
    client.connect("/tmp/rofi_notification_daemon")
    ConnectionRefusedError: [Errno 111] Connection refused 

On budgie, where i intend to use rofication, i tried the same process as above, with the same results. Only when I start the daemon from ~/.config/autostart, will the gui start. Though it still wont pull in any notifications. 

EDIT 2:

After more digging around, I have concluded rofication will not work with budgie, or maybe more accurately - budgie will not work with rofication. As far as I can understand budgies implementation of desktop notifications is essentially the same as gnome. The notification server is built in and cannot be fully stopped or replaced. I guess I should not be surprised....closing this non-issue.

**Comment by DaveDavenport** [comment]
to bad. (I did not get around trying it out yet).

**Comment by vredesbyyrd** [comment]
yeah, bummer indeed. Would have been nice to use it on my low powered acer cloudbook running arch/budgie. Not a big fan of budgies 'raven sidebar', but really enjoying the de otherwise so rofication was the perfect thing to take its place.  

There might be a way around the built in notification server for gnome/budgie, but thus far its beyond me.
