### ISSUE TITLE
Feature request or hint: prevent UI flicker when deleting notifications from Rofi

### ISSUE THREAD

**Issue by kgilmer** [DaveDavenport/Rofication#2]
I <3 Rofication and would like to add it to Regolith.  I have been running it for several weeks now and haven't had any issues.  One usability problem I face however is that when the python script calls into Rofi to display notifications, and the user does something like delete a notifcation, the flow is that this exits Rofi, back into python, and then loop.  This is fine and makes sense except that my Rofi theme is "full screen" and the rapid interaction of deleting notifications is unpleasant due to see.  Rofi has a lot of configuration options that I don't fully understand so I hold out hope that there maybe some way that either the deletion logic can be implemented somehow within Rofi to avoid this back-and-forth with the python script (and hence preventing the flicker), or some other approach that escapes me.

Any suggestions?

**Comment by DaveDavenport** [comment]
only way to do that atm is write a modi-script that implement the same functionality, or a C -plugin for rofi.

**Comment by kgilmer** [comment]
Looking thru the source and docs it's not clear to me what a modi is. Is there an example?

**Comment by DaveDavenport** [comment]
https://github.com/davatorium/rofi/blob/next/Examples/test_script_mode.sh

**Comment by kgilmer** [comment]
Thank you!
