### ISSUE TITLE
xbindkeysrc shortcut to run  rofication-gui.py

### ISSUE THREAD

**Issue by plum** [DaveDavenport/Rofication#4]
Hi, a very good impementation of notiufiucations, I think. Thanks.
I'm sure you'll appreciate the importance of running rofication-gui.py form a keyboard shortcut, as I do; I cannot get any usual method to work though. I can get all other rofi, pass and buku scripts to execute from .xbindkeysrc,  just not this python script (unlike th e thers which aren't triggering python scripts).

I tried three alternative forms which both work from the terminal:
"/usr/bin/rofication-gui.py" and alternitively, 
python3 "/usr/bin/rofication-gui.py",
/usr/bin/python "/usr/bin/rofication-gui.py"

I also tried tried to trigger a bash script:

#!bin/bash
/usr/bin/rofication-gui.py.

Running the bash script above from the terminal give this error,  "failed execute child process; permission denied"

The python script runs form a terminal (urxvt), as well as from the rofi drun, even without path specified. 
I note tha the python script itself, appears to specify full paths, so no prolem there.
Thanks in advance, 
John

**Comment by DaveDavenport** [comment]
This is not an issue with the rofication-gui.py script. Given it launches fine from terminal and rofi. 

I don't know how xbindkeysrc works, so for problems with that you should check their support channel.

for that bash script, your shebang is wrong. (relative path, not absolute).

**Comment by plum** [comment]
thanks Dave. Forgive me. I hope it may help someone else!

**Comment by DaveDavenport** [comment]
> thanks Dave. Forgive me. I hope it may help someone else!

No problem. I hope you get it resolved.
