### ISSUE TITLE
Ability to let notificaitons overwrite each other

### ISSUE THREAD

**Issue by nrktkt** [DaveDavenport/Rofication#5]
Currently each notification creates a persistent entry. With applications that emit several notifications, this can cause the number of unread notifications to build up in a non-productive way.

For example, spotify has a notification each time a new song starts playing. If you don't dismiss that notification and listen to 10 songs, you'll have 10 notifications that you have to go back and delete. 
If it were possible to configure rofication such that a new spotify notification would automatically delete any previous spotify notification, then we could open our notification area and always only see the current/last played song. This is more in line with the behavior we'd expect on mobile or windows 10.

A more advanced version of this would be to have a way to subgroup notifications from applications. For example on slack, having only one outstanding notification per channel would prevent us from having hundreds of notifications outstanding if we were to miss a slack conversation.

**Comment by DaveDavenport** [comment]
It has a option for this, in the `rofication-daemon.py` source file you can set:
```
single_notification_app
```
with a list of apps where it should only give last

**Comment by nrktkt** [comment]
awesome, thanks Dave
